correct command to get GREEN_LB_URL

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -84,21 +84,20 @@ jobs:
       - run:
           name: Smoke test
           command: |
-            GREEN_LB_URL=$(cat ~/project/green_lb_url.txt)
+            GREEN_LB_URL=$(cat ~/project/green_lb_url.txt | tail -1)
             echo ${GREEN_LB_URL}
-          #  curl -s http://${GREEN_LB_URL} | grep '"success": true'
-          #  retval=$?
+            curl -s http://${GREEN_LB_URL} | grep '"success": true'
+            retval=$?
 
-          #  echo ${GREEN_LB_URL}
-          #  echo $retval
-          #  if [ $retval -eq 0 ]
-          #  then
-          #     echo "URL OK"
-          #     exit 0
-          #  else
-          #     echo "URL Fail"
-          #     exit 1
-          #  fi
+            echo $retval
+            if [ $retval -eq 0 ]
+            then
+               echo "URL OK"
+               exit 0
+            else
+               echo "URL Fail"
+               exit 1
+            fi
 
 
 workflows:
